"""empty message

Revision ID: 799165ee2d54
Revises: fb18173055bf
Create Date: 2025-03-10 03:09:55.417660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799165ee2d54'
down_revision = 'fb18173055bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
